### PR TITLE
textures

### PR DESCRIPTION
**Pull request by pcblockgermany**
Added textures for armor and staffs.

### CODE REVIEW

**Comment by TheXFactor117** [comment]
Might not use all of them, but I may have a use for a few :).

**Comment by pcblockgermany** [comment]
No problem, that's the intention of those :D 
(If you want other colors, nearly every painting program has a tint/color correction tool)

**Comment by TheXFactor117** [comment]
Astrill, for me, would be a pink color. Vexal is spot on, and Malachite could be a bit more bluish-green.

**Comment by pcblockgermany** [comment]
sorry, only saw it now, colors updated

**Pull request merged**
